export const PLACE_ROBOT = 'PLACE_ROBOT';
export const PLACE_ROBOT_SUCCESS = 'PLACE_ROBOT_SUCCESS';
export const PLACE_ROBOT_FAILED = 'PLACE_ROBOT_FAILED';

export const MOVE_ROBOT = 'MOVE_ROBOT';
export const MOVE_ROBOT_SUCCESS = 'MOVE_ROBOT_SUCCESS';
export const MOVE_ROBOT_FAILED = 'MOVE_ROBOT_FAILED';

export const GET_ROBOT_STATE = 'GET_ROBOT_STATE';
export const ROBOT_STATE_RECEIVED = 'ROBOT_STATE_RECEIVED';
export const ROBOT_STATE_REQUEST_FAILED = 'ROBOT_STATE_REQUEST_FAILED';